### ISSUE TITLE
WithdrawBalance method is using the old transfer method.

### ISSUE THREAD

**Issue by FrankNFT-labs** [LightArtists/light-smart-contracts#1]
In ThreeChiefOfficersWithRoyalties.sol, method :

    /// @notice Collect Ether from this contract
    function withdrawBalance() external {
        if (msg.sender != _financialOfficer) {
            revert NotFinancialOfficer();
        }
        _financialOfficer.transfer(address(this).balance);
    }

There is a gas limit of 2300 gas on the transfer method, **making it likely to fail** if you transfer the money to a contract that does more then just logging it (for instance a vault). 

The call method  is the recommended way of sending ETH to a smart contract.

**FIX:**  use a method like this (Taken from the ERC721F - by me) :

    /**
    * Helper method to allow ETH withdraws.
    */
    function _withdraw(address _address, uint256 _amount) internal {
        (bool success, ) = _address.call{ value: _amount }("");
        require(success, "Failed to widthdraw Ether");
    }

**Comment by fulldecent** [comment]
Thank you for sharing. This is just a quick note and is not our official response, but I just wanted to let you know we are using the recommended approach from https://docs.soliditylang.org/en/v0.8.15/common-patterns.html#withdrawal-pattern. You may also want to [report an issue there](https://github.com/ethereum/solidity/issues/new?template=documentation_issue.md&projects=ethereum/solidity/43&labels=documentation+%3Abook%3A) to recommend this broader approach by default.

**Comment by fulldecent** [comment]
Thank you for starting ERC721F to investigate optimizations. Once you have gas profiling instrumentation set up there, I'll be interested to see your progress on those initiatives. And thank you also for the presentation!

---

We are reviewing this approach you recommended. This is set up at https://github.com/LightArtists/light-smart-contracts/pull/3

**Comment by FrankNFT-labs** [comment]
The profiler will be for after summer, together with some reference implementations. I'll keep you posted.

**Comment by fulldecent** [comment]
This entry is eligible for the bug bounty, we really appreciate your review!

Overall, we reviewed several scenarios where this might have an impact. The CFO account would need to be set to some smart contract that requires a certain amount of gas to receive Ether. Because we are using three-party owners, we can prevent any loss of Ether by switching to another CFO.

But still this was a worthy suggestion and we have applied it in the production application.

For the bug bounty rating:

- This affects only the administrator (CFO) and only in the situation that they have created some smart contract to withdraw Ether value which costs a certain amount of gas. And only temporarily because a different CFO can be assigned. This is assigned a "likelihood" of low. 
- When effected, this results in the Ether not being sent. The function already fails gracefully in the event of a failed transaction (it throws) and the Ether is not lost. So a fair "impact" is somewhere between low and medium.
- Applying this rubric and the scoring rules, this is a "severity" of notable or low.

You win! 🎊 

Please contact hello@light.art to collect your prize t-shirt. Additionally, although there is no cash prize for this severity level, we did want to plus you up and have an added extra USD 500 for you. Finally, please let me know if we may credit you on Twitter publicly for this contribution and please remind us your handle.

---

Thank you again, we opened this for discussion in the Solidity project broadly. Here is the issue https://github.com/ethereum/solidity/issues/13371

**Comment by FrankNFT-labs** [comment]
sure no problem for the credit on twitter. for the USD, i suppose you will do that in crypto in some kind of stable coin? if yes, you can send to frankNFT.eth

**Comment by dapppunk** [comment]
Thank you again for your contribution. We have send 500 USDC to FrankNFT.eth
https://etherscan.io/tx/0xaafc0c47788485580a53f72ef5b960d25935f7dea4eb86d873c6a69d4c71e08f

**Comment by fulldecent** [comment]
@FrankNFT-labs please remind us your Twitter handle. Your ENS points to https://twitter.com/FrankPoncelet which does not exist or was deleted.

**Comment by fulldecent** [comment]
Ah I think it's this https://twitter.com/light_artists/status/1561558132802797569 // Tweeted it!

**Comment by FrankNFT-labs** [comment]
thx for that heads up, i'll update my ENS
